name: ilocate
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8               # Style icons for the app
  intl: ^0.18.1                         # Date Formatter
  firebase_core: ^3.15.2                # Firebase SDK for Initialization
  firebase_database: ^11.0.0            # Firebase Realtime DB
  bcrypt: ^1.1.3                        # For hashing password
  shared_preferences: ^2.2.2            # For Password Reset
  google_maps_flutter: ^2.5.0           # For Google Maps display
  #geolocator: ^14.0.2                   # To get the rescuer's current location
  #flutter_polyline_points: ^1.0.0       # To generate route points between rescuer and wearer

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Logo1.png
