// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMcjKZov3SOUngPe1AlJBwwifOhA4FxMU',
    appId: '1:546151450200:web:cbac0c160e1d20080eac2d',
    messagingSenderId: '546151450200',
    projectId: 'fir-ttn-lorawan',
    authDomain: 'fir-ttn-lorawan.firebaseapp.com',
    databaseURL: 'https://fir-ttn-lorawan-default-rtdb.firebaseio.com',
    storageBucket: 'fir-ttn-lorawan.firebasestorage.app',
    measurementId: 'G-F3MTXH2G96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnHvU8lknnb4eRRJ0guDKUrQK7bfJpBQM',
    appId: '1:546151450200:android:06a501b6b9f8d8190eac2d',
    messagingSenderId: '546151450200',
    projectId: 'fir-ttn-lorawan',
    databaseURL: 'https://fir-ttn-lorawan-default-rtdb.firebaseio.com',
    storageBucket: 'fir-ttn-lorawan.firebasestorage.app',
  );
}
